/**
 * 流亡黯道官方繁體中文術語對應表
 * 參考官方資料與 PoEDB (https://poedb.tw/tw/Timeless_Jewel)
 */

/** 永恆珠寶名稱：ID → 繁體中文 */
export const jewelNames: Record<number, string> = {
  1: '輝煌的虛榮', // Glorious Vanity
  2: '致命的驕傲', // Lethal Pride
  3: '殘酷的紀律', // Brutal Restraint
  4: '激進的信仰', // Militant Faith
  5: '優雅的高傲', // Elegant Hubris
  6: '英勇的悲劇' // Heroic Tragedy
};

/** 征服者（傳說人物）名稱 */
export const conquerorNames: Record<string, string> = {
  // 輝煌的虛榮 (1)
  Xibaqua: '賽巴昆',
  Zerphi: '澤佛伊',
  Ahuana: '阿呼阿娜',
  Doryani: '多里亞尼',

  // 致命的驕傲 (2)
  Kaom: '岡姆',
  Rakiata: '拉其塔',
  Kiloava: '基洛阿瓦',
  Akoya: '阿冦亞',

  // 殘酷的紀律 (3)
  Deshret: '德熱雷',
  Balbala: '貝爾巴拉',
  Asenath: '安賽娜絲',
  Nasima: '納西瑪',

  // 激進的信仰 (4)
  Venarius: '維那利斯',
  Maxarius: '瑪薩里歐斯',
  Dominus: '神主',
  Avarius: '伊爾莉斯',

  // 優雅的高傲 (5)
  Cadiro: '卡迪羅',
  Victario: '維多里奧',
  Chitus: '切特斯',
  Caspiro: '卡斯皮羅',

  // Heroic Tragedy (6)
  Vorana: '沃拉娜',
  Uhtred: '烏特雷',
  Medved: '梅德偉'
};

const exactLeagueNames: Record<string, string> = {
  Standard: '標準模式',
  Hardcore: '專家模式',
  'Solo Self-Found': '自力',
  SSF: '自力',
  Ruthless: '殘暴',
  'Hardcore Ruthless': '殘暴（專家）',
  'Ruthless Hardcore': '殘暴（專家）',
  'Solo Self-Found Ruthless': '殘暴「自力」',
  'Ruthless Solo Self-Found': '殘暴「自力」',
  'SSF Ruthless': '殘暴「自力」',
  'Ruthless SSF': '殘暴「自力」',
  'Hardcore Solo Self-Found Ruthless': '殘暴（專家）「自力」',
  'Hardcore Ruthless Solo Self-Found': '殘暴（專家）「自力」',
  'Ruthless Hardcore Solo Self-Found': '殘暴（專家）「自力」',
  'HC Ruthless': '殘暴（專家）',
  'HC SSF Ruthless': '殘暴（專家）「自力」',
  'HC Ruthless SSF': '殘暴（專家）「自力」',
  Mirage: '遠古蜃景',
  'Hardcore Mirage': '遠古蜃景（專家）',
  'Solo Self-Found Mirage': '遠古蜃景「自力」',
  'Hardcore Solo Self-Found Mirage': '遠古蜃景（專家）「自力」',
  'SSF Mirage': '遠古蜃景「自力」',
  'HC Mirage': '遠古蜃景（專家）',
  'Ruthless Mirage': '遠古蜃景. 殘暴',
  'Hardcore Ruthless Mirage': '遠古蜃景. 殘暴（專家）',
  'HC Ruthless Mirage': '遠古蜃景. 殘暴（專家）'
};

const leaguePhraseNames: Array<[string, string]> = [
  ['Solo Self-Found', '自力'],
  ['Hardcore', '專家'],
  ['Ruthless', '殘暴'],
  ['Standard', '標準'],
  ['Mirage', '蜃景'],
  ['SSF', '自力'],
  ['HC', '專家']
];

const exactLeagueNamesLower = Object.fromEntries(
  Object.entries(exactLeagueNames).map(([key, value]) => [key.toLowerCase(), value])
) as Record<string, string>;

/** 屬性描述 (Stats) 對應表：ID → 官方繁體中文模板 */
export const statDescriptions: Record<number, string> = {
  25: '增加 #% 法術傷害',
  26: '增加 #% 物理傷害',
  42: '增加 #% 火焰傷害',
  49: '增加 #% 冰冷傷害',
  56: '增加 #% 閃電傷害',
  63: '增加 #% 混沌傷害',
  70: '增加 #% 攻擊速度',
  95: '+#% 暴擊加成',
  117: '增加 #% 護甲',
  124: '增加 #% 生命最大值',
  134: '增加 #% 能量護盾最大值',
  150: '+#% 閃電抗性',
  216: '增加 #% 施放速度',
  434: '增加 #% 範圍效果',
  482: '將 #% 物理傷害轉換為火焰傷害',
  483: '將 #% 物理傷害轉換為冰冷傷害',
  484: '將 #% 物理傷害轉換為閃電傷害',
  488: '召喚生物增加 #% 傷害',
  554: '增加 #% 暴擊率',
  556: '增加 #% 法術暴擊率',
  593: '傷害穿透 #% 火焰抗性',
  594: '傷害穿透 #% 冰冷抗性',
  595: '傷害穿透 #% 閃電抗性',
  619: '增加 #% 範圍傷害',
  943: '+#% 火焰抗性上限',
  944: '+#% 冰冷抗性上限',
  945: '+#% 閃電抗性上限',
  946: '+#% 混沌抗性上限',
  2133: '#% 混沌傷害轉為生命偷取',
  3108: '#% 物理傷害轉為生命偷取',
  3109: '#% 火焰傷害轉為生命偷取',
  3110: '#% 冰冷傷害轉為生命偷取',
  3111: '#% 閃電傷害轉為生命偷取',
  5815: '#% 機率造成雙倍傷害',
  8835: '#% 法術傷害轉為能量護盾偷取',
  9091: '你造成的流血傷害加速 #%',
  9772: '擊中時有 #% 機率造成凋零狀態，持續 2 秒',
  14775: '+#% 壓抑法術傷害機率',
  209: '增加 #% 燃燒傷害',
  447: '獲得等同 #% 物理傷害的額外火焰傷害',
  573: '+# 力量',
  1294: '+#% 近戰暴擊加成',
  1361: '增加 #% 近戰傷害',
  2031: '增加 #% 力量',
  8177: '擊中時有 #% 機率恐嚇敵人，持續 4 秒',
  448: '獲得等同 #% 物理傷害的額外冰冷傷害',
  486: '增加 #% 元素傷害',
  579: '+# 敏捷',
  1404: '擊殺時獲得 # 秒猛攻',
  2030: '增加 #% 敏捷',
  9090: '你造成的中毒傷害加速 #%',
  9711: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為火焰傷害',
  9712: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為冰冷傷害',
  9713: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為閃電傷害',
  9714: '若你至少有 150 個奉獻，獲得等同 #% 最大魔力的額外最大能量護盾',
  9716: '若你至少有 150 個奉獻，+# 最小耐力球',
  9717: '若你至少有 150 個奉獻，+# 最小暴擊球',
  9718: '若你至少有 150 個奉獻，+# 最小狂怒球',
  9721: '若你至少有 150 個奉獻，+#% 全部最大抗性',
  9722: '若你至少有 150 個奉獻，擊中時有 #% 機率造成火焰曝曬',
  9723: '若你至少有 150 個奉獻，擊中時有 #% 機率造成冰冷曝曬',
  9724: '若你至少有 150 個奉獻，擊中時有 #% 機率造成閃電曝曬',
  186: '擊中時有 #% 機率獲得 1 個狂怒球',
  490: '增加 #% 近戰物理傷害',
  1251: '暴擊時有 #% 機率獲得 1 個暴擊球',
  1654: '每個狂怒球增加 #% 傷害',
  3392: '每個耐力球增加 #% 傷害',
  6042: '增加 #% 流血傷害',
  6048: '增加 #% 攻擊技能的火焰傷害',
  6049: '增加 #% 攻擊技能的冰冷傷害',
  6050: '增加 #% 攻擊技能的閃電傷害',
  6136: '每個暴擊球增加 #% 傷害',
  7499: '若近期內被擊中，每秒獲得 1 個耐力球',
  23: '裝備的盾牌增加 #% 防禦',
  84: '增加 #% 全域命中值',
  97: '你承受的暴擊額外傷害減少 #%',
  108: '減少 #% 敵人暈眩門檻',
  120: '增加 #% 閃避值',
  122: '每個狂怒球增加 #% 閃避值',
  125: '增加 #% 生命最大值',
  129: '增加 #% 魔力最大值',
  131: '增加 #% 魔力回復率',
  135: '增加 #% 能量護盾最大值',
  139: '增加 #% 能量護盾充能率',
  142: '+#% 全部元素抗性',
  146: '+#% 火焰抗性',
  148: '+#% 冰冷抗性',
  152: '+#% 混沌抗性',
  161: '召喚生物增加 #% 生命最大值',
  177: '增加 #% 投射物速度',
  179: '增加 #% 移動速度',
  188: '擊中時有 #% 機率獲得 1 個狂怒球',
  192: '有 #% 機率避免被冰緩',
  195: '有 #% 機率避免被感電',
  211: '增加 #% 燃燒傷害',
  217: '增加 #% 技能效果持續時間',
  218: '增加 #% 施放速度',
  342: '增加 #% 敵人暈眩持續時間',
  436: '增加 #% 範圍效果',
  449: '獲得等同 #% 物理傷害的額外火焰傷害',
  450: '獲得等同 #% 物理傷害的額外冰冷傷害',
  453: '每秒回復 #% 生命',
  457: '擊中時總能造成冰凍',
  462: '增加 #% 藥劑充能獲取',
  485: '將 #% 物理傷害轉換為冰冷傷害',
  492: '增加 #% 近戰物理傷害',
  500: '增加 #% 投射物傷害',
  558: '增加 #% 法術暴擊率',
  575: '+# 力量',
  581: '+# 敏捷',
  596: '傷害穿透 #% 冰冷抗性',
  597: '傷害穿透 #% 閃電抗性',
  613: '有 #% 機率點燃敵人',
  621: '增加 #% 範圍傷害',
  622: '有 #% 機率避免元素異常狀態',
  661: '有 #% 機率造成感電狀態',
  741: '增加 #% 藥劑效果持續時間',
  846: '你的光環增加 #% 範圍效果',
  947: '+#% 混沌抗性上限',
  975: '擊中時有 #% 機率致盲敵人',
  1036: '額外 #% 物理傷害減免',
  1084: '+#% 攻擊格擋率',
  1254: '暴擊時有 #% 機率獲得 1 個暴擊球',
  1297: '+#% 近戰暴擊加成',
  1332: '你造成的點燃傷害加速 #%',
  1346: '增加 #% 圖騰放置速度',
  1356: '擊殺時有 #% 機率獲得 1 個狂怒球',
  1358: '增加 #% 近戰暴擊率',
  1365: '增加 #% 近戰傷害',
  1368: '格擋時回復 # 生命',
  1391: '增加 #% 你的詛咒效果',
  1408: '擊殺時獲得 # 秒猛攻',
  1659: '每個狂怒球增加 #% 傷害',
  1793: '增加 #% 圖騰傷害',
  1909: '增加 #% 攻擊與施放速度',
  1979: '增加 #% 持續傷害',
  2034: '增加 #% 敏捷',
  2035: '增加 #% 力量',
  2095: '+#% 法術格擋率',
  2137: '#% 的混沌傷害轉為生命偷取',
  2612: '增加 #% 攻擊傷害',
  2666: '增加 #% 敵人身上的元素異常狀態持續時間',
  2701: '#% 攻擊傷害轉為生命偷取',
  3116: '#% 物理傷害轉為生命偷取',
  3117: '#% 火焰傷害轉為生命偷取',
  3118: '#% 冰冷傷害轉為生命偷取',
  3119: '#% 閃電傷害轉為生命偷取',
  3376: '增加 #% 中毒傷害',
  3403: '每個耐力球增加 #% 傷害',
  3576: '增加 #% 冰緩效果',
  3577: '增加 #% 感電效果',
  3853: '你的技能增加 #% 非詛咒光環效果',
  3892: '擊殺時有 #% 機率獲得 1 個耐力球',
  4968: '增加 #% 投射物攻擊傷害',
  5554: '增加 #% 戰吼增益效果',
  5856: '有 #% 機率造成雙倍傷害',
  6083: '增加 #% 流血傷害',
  6089: '增加 #% 攻擊技能的火焰傷害',
  6090: '增加 #% 攻擊技能的冰冷傷害',
  6091: '增加 #% 攻擊技能的閃電傷害',
  6126: '有 #% 機率避免被暈眩',
  6178: '每個暴擊球增加 #% 傷害',
  6350: '增加 #% 非傷害型異常狀態效果',
  7546: '若近期內被擊中，每秒獲得 # 個耐力球',
  8230: '擊中時有 #% 機率恐嚇敵人 4 秒',
  8271: '每個耐力球增加 #% 護甲',
  8273: '每個暴擊球增加 #% 能量護盾最大值',
  8889: '#% 法術傷害轉為能量護盾偷取',
  8945: '增加 #% 詛咒技能持續時間',
  9127: '你造成的中毒傷害加速 #%',
  9128: '你造成的流血傷害加速 #%',
  9431: '內觀信念',
  9441: '青春永駐',
  9483: '腐化之魂',
  9484: '不可知論',
  9485: '神聖血肉',
  9613: '側身之擊',
  9622: '至高．頹廢',
  9658: '+# 獻祭',
  9666: '風魔舞者',
  9731: '血之力量',
  9748: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為火焰傷害',
  9749: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為冰冷傷害',
  9750: '若你至少有 150 個奉獻，將 #% 物理傷害轉換為閃電傷害',
  9751: '若你至少有 150 個奉獻，獲得等同 #% 最大魔力的額外最大能量護盾',
  9752: '若你至少有 150 個奉獻，法術擊中時獲得秘能波動',
  9753: '若你至少有 150 個奉獻，+# 最小耐力球',
  9754: '若你至少有 150 個奉獻，+# 最小暴擊球',
  9755: '若你至少有 150 個奉獻，+# 最小狂怒球',
  9756: '若你至少有 150 個奉獻，在奉獻地面上時免疫元素異常狀態',
  9757: '若你至少有 150 個奉獻，額外 #% 物理傷害減免',
  9758: '若你至少有 150 個奉獻，+#% 全部最大抗性',
  9759: '若你至少有 150 個奉獻，擊中時有 #% 機率造成火焰曝曬',
  9760: '若你至少有 150 個奉獻，擊中時有 #% 機率造成冰冷曝曬',
  9761: '若你至少有 150 個奉獻，擊中時有 #% 機率造成閃電曝曬',
  9777: '至高自我',
  9809: '擊中時有 #% 機率造成凋零狀態，持續 2 秒',
  11937: '超凡脫俗',
  12097: '不朽野望',
  12138: '使用藥劑時有 #% 機率獲得鍊金術師的天才',
  14769: '增加 #% 技能的魔力保留效能',
  14804: '+#% 壓抑法術傷害機率',
  14879: '+# 最大護體',
  20665: '近戰擊中時獲得 # 層盛怒',
  // ── 基石天賦效果 (Keystone Effects) ──
  9486: '50% 承受的冰冷與閃電傷害轉化為火焰傷害、少 50% 冰冷與閃電抗性',
  11892: '技能消耗 +3 盛怒、若近期你擊中敵人，每秒失去 1 盛怒',
  11867: '每個空的藥劑欄位，每 5 秒獲得 4 藥劑充能',
  9454: '不能使用頭盔、你的暴擊機率是幸運的、你的暴擊傷害是幸運的、敵人對你的暴擊傷害是幸運的',
  9651: '你被致盲、致盲不影響你的照亮範圍、致盲時增加 25% 更多近戰暴擊率',
  9446: '最大魔力的 80% 轉換為該數值雙倍的護甲',
  9435: '附近友方和敵人與你共享耐力、狂怒和暴擊球、擊中你的敵人有 10% 機率獲得 1 顆球',
  11868: '無視屬性需求、屬性不提供額外加成'
};

/** 特殊核心與卓越天賦（英文對應繁體中文） */
export const alternateSkillNames: Record<string, string> = {
  'Divine Flesh': '神聖血肉',
  'Immortal Ambition': '不朽野望',
  'Corrupted Soul': '腐化之魂',
  'Strength of Blood': '血之力量',
  'Tempered by War': '戰爭淬煉',
  Chainbreaker: '除鏈師',
  'The Traitor': '叛徒',
  'Dance with Death': '與死共舞',
  'Second Sight': '先見之明',
  Transcendence: '超凡脫俗',
  'Inner Conviction': '內觀信念',
  'Power of Purpose': '力量之意',
  'Supreme Decadence': '至高．頹廢',
  'Supreme Grandstanding': '至高．譁眾',
  'Supreme Ostentation': '至高．炫耀',
  'Black Scythe Training': '黑鐮之訓',
  'Celestial Mathematics': '星界計算',
  'The Unbreaking Circle': '不滅之環',
  'Ritual of Immolation': '獻祭儀式',
  'Revitalising Flames': '復甦業火',
  'Flesh to Flames': '獄火焚身',
  'Ritual of Stillness': '靜默儀式',
  'Revitalising Frost': '復甦寒霜',
  'Flesh to Frost': '寒霜凍身',
  'Ritual of Thunder': '雷霆儀式',
  'Revitalising Lightning': '復甦雷霆',
  'Flesh to Lightning': '雷霆灌身',
  'Ritual of Might': '權勢儀式',
  'Revitalising Winds': '復甦狂風',
  'Bloody Savagery': '血腥殘暴',
  'Ritual of Shadows': '暗影儀式',
  'Revitalising Darkness': '復甦暗黑',
  'Thaumaturgical Aptitude': '奇術之資',
  Hierarchy: '階級體制',
  'Exquisite Pain': '極苦之痛',
  'Ritual of Flesh': '血肉儀式',
  'Flesh Worship': '肉體崇拜',
  'Ritual of Memory': '記憶儀式',
  'Automaton Studies': '機甲研究',
  'Construct Studies': '建構研究',
  'Energy Flow Studies': '能流研究',
  'Soul Worship': '靈魂崇拜',
  'Blood-Quenched Bulwark': '抑血壁壘',
  'Thaumaturgical Protection': '奇術禦防',
  'Jungle Paths': '叢林之道',
  'Temple Paths': '神殿之道',
  'Commanding Presence': '指揮之環',
  'Ancient Hex': '古典魔女',
  'Cult of Fire': '烈火崇拜',
  'Cult of Ice': '冰霜崇拜',
  'Cult of Lightning': '雷霆崇拜',
  'Cult of Chaos': '混沌崇拜',
  'Might of the Vaal': '瓦爾．強權',
  'Legacy of the Vaal': '瓦爾．不朽',
  Devotion: '還願',
  'Heated Devotion': '熱情的奉獻',
  'Calming Devotion': '冷靜的奉獻',
  'Thundrous Devotion': '慷慨的奉獻',
  'Thoughts and Prayers': '思想和信徒',
  Zealot: '狂熱',
  'Enduring Faith': '耐力信念',
  'Powerful Faith': '暴擊信念',
  'Frenzied Faith': '狂怒信念',
  Cloistered: '神隱',
  "Martyr's Might": '烈士之力',
  'Intolerance of Sin': '難忍罪孽',
  'Smite the Wicked': '重挫邪惡',
  'Smite the Ignorant': '重挫無知',
  'Smite the Heretical': '重挫異教',
  'Price of Glory': '榮耀代價',
  'Flawless Execution': '完美行動',
  'Brutal Execution': '殘暴行動',
  'Eternal Resilience': '永恆韌性',
  'Eternal Fortitude': '永恆剛毅',
  'Eternal Dominance': '永恆統御',
  'Eternal Fervour': '永恆熱情',
  'Eternal Adaptiveness': '永恆適性',
  'Eternal Bloodlust': '永恆嗜血',
  'Eternal Subjugation': '永恆抑制',
  'Eternal Separation': '永恆隔離',
  'Eternal Exploitation': '永恆開發',
  'Rites of Lunaris': '月影儀式',
  'Rites of Solaris': '日耀儀式',
  'Virtue Gem Surgery': '古靈寶石手術',
  'Rural Life': '鄉村生活',
  'City Walls': '古城之牆',
  'Sceptre Pinnacle': '王權之巔',
  'Secret Tunnels': '秘密通道',
  'Purity Rebel': '純淨反叛',
  Superiority: '優越',
  'Slum Lord': '貧民君主',
  'Axiom Warden': '典獄長格言',
  'Gemling Inquisition': '古靈審判所',
  'Gemling Ambush': '古靈伏擊',
  'Night of a Thousand Ribbons': '千縷絲之夜',
  "Bloody Flowers' Rebellion": '太腥花之亂',
  "Chitus' Heart": '切特斯之心',
  'Gemling Training': '古靈訓練',
  "Rigwald's Might": '瑞佛之力',
  "Geofri's End": '吉爾菲的結局',
  "Lioneye's Focus": '獅眼的專注',
  "Voll's Coup": '福爾的妙計',
  "Dialla's Wit": '達拉的智慧',
  'Discerning Taste': '鑑賞之味',
  'Gleaming Legion': '閃耀軍閥',
  'Shadowy Streets': '陰暗巷道',
  'Crematorium Worker': '火葬場之徒',
  'Street Urchin': '街邊頑童',
  'Baleful Augmentation': '險惡增幅',
  'With Eyes Open': '睜大雙眼',
  'Robust Diet': '生酮飲食',
  'Pooled Resources': '集資',
  Laureate: '桂冠',
  'War Games': '戰爭遊戲',
  'Freshly Brewed': '鮮釀',
  'Warding Flasks': '護佑藥劑',
  'Starlight Swig': '痛飲星光',
  'Enduring Sigil': '耐力符印',
  'Powering Sigil': '暴擊符印',
  'Frenzying Sigil': '狂怒符印',
  'Fortified Ward': '護體保護',
  'Elusive Ward': '靈巧保護',
  'Crown of Kalguur': '卡爾葛之冠',
  'Grip of Kalguur': '卡爾葛之握',
  'Stride of Kalguur': '卡爾葛之步',
  'Persisting Drive': '恆續動能',
  'Shattered Piercing': '粉碎穿透',
  'Vengeful Runes': '復仇符文',
  "Mage's Ward": '巫師之護',
  "Warrior's Ward": '戰士之護',
  'Starborn Birth': '星裔之誕',
  'Pure Faith': '純粹信仰',
  'Magic Faith': '魔法信仰',
  'Guile Faith': '詭詐信仰',
  'Resolute Faith': '堅決信仰',
  'Starsoaked Time': '星浸時限',
  'Etched Runes': '蝕刻符文',
  'Cleansing Runes': '淨化符文',
  'Regenerative Runes': '回復符文',
  'Heroic Tragedy': '英勇的悲劇',

  // ── 基礎屬性類別（小天賦替代名稱） ──
  'Fire Damage': '火焰傷害',
  'Cold Damage': '冰冷傷害',
  'Lightning Damage': '閃電傷害',
  'Physical Damage': '物理傷害',
  'Chaos Damage': '混沌傷害',
  'Minion Damage': '召喚物傷害',
  'Attack Damage': '攻擊傷害',
  'Spell Damage': '法術傷害',
  'Area Damage': '範圍傷害',
  'Projectile Damage': '投射物傷害',
  'Damage Over Time': '持續傷害',
  'Area of Effect': '範圍效果',
  'Projectile Speed': '投射物速度',
  'Critical Strike Chance': '暴擊率',
  'Critical Strike Multiplier': '暴擊加成',
  'Attack Speed': '攻擊速度',
  'Cast Speed': '施放速度',
  'Movement Speed': '移動速度',
  'Ignite Chance': '點燃機率',
  'Freeze Chance': '冰凍機率',
  'Shock Chance': '感電機率',
  'Skill Duration': '技能持續時間',
  Life: '生命',
  Mana: '魔力',
  'Mana Regeneration': '魔力回復',
  Armour: '護甲',
  Evasion: '閃避',
  'Energy Shield': '能量護盾',
  Block: '格擋',
  'Spell Block': '法術格擋',
  'Avoid Elemental Ailments': '避免元素異常狀態',
  'Spell Suppression': '法術壓抑',
  'Aura Effect': '光環效果',
  'Curse Effect': '詛咒效果',
  'Fire Resistance': '火焰抗性',
  'Cold Resistance': '冰冷抗性',
  'Lightning Resistance': '閃電抗性',
  'Chaos Resistance': '混沌抗性',

  // ── 特殊核心天賦（補遺） ──
  'Glancing Blows': '側身之擊',
  'Supreme Ego': '至高．自我',
  'The Agnostic': '不可知論',
  'Wind Dancer': '風魔舞者',
  'Eternal Youth': '青春永駐'
};

/** 附加天賦 Addition ID → 繁體中文 */
export const alternateAdditionNames: Record<string, string> = {
  // ── 瓦爾（小天賦附加） ──
  'vaal_small_fire_damage': '火焰傷害',
  'vaal_small_cold_damage': '冰冷傷害',
  'vaal_small_lightning_damage': '閃電傷害',
  'vaal_small_physical_damage': '物理傷害',
  'vaal_small_chaos_damage': '混沌傷害',
  'vaal_small_minion_damage': '召喚物傷害',
  'vaal_small_attack_damage': '攻擊傷害',
  'vaal_small_spell_damage': '法術傷害',
  'vaal_small_area_damage': '範圍傷害',
  'vaal_small_projectile_damage': '投射物傷害',
  'vaal_small_damage_over_time': '持續傷害',
  'vaal_small_area_of_effect': '範圍效果',
  'vaal_small_projectile_speed': '投射物速度',
  'vaal_small_critical_strike_chance': '暴擊率',
  'vaal_small_critical_strike_multiplier': '暴擊加成',
  'vaal_small_attack_speed': '攻擊速度',
  'vaal_small_cast_speed': '施放速度',
  'vaal_small_movement_speed': '移動速度',
  'vaal_small_chance_to_ignite': '點燃機率',
  'vaal_small_chance_to_freeze': '冰凍機率',
  'vaal_small_chance_to_shock': '感電機率',
  'vaal_small_duration': '技能持續時間',
  'vaal_small_life': '生命',
  'vaal_small_mana': '魔力',
  'vaal_small_mana_regeneration': '魔力回復',
  'vaal_small_armour': '護甲',
  'vaal_small_evasion': '閃避',
  'vaal_small_energy_shield': '能量護盾',
  'vaal_small_attack_block': '攻擊格擋',
  'vaal_small_spell_block': '法術格擋',
  'vaal_small_attack_dodge': '攻擊躲避',
  'vaal_small_spell_dodge': '法術躲避',
  'vaal_small_aura_effect': '光環效果',
  'vaal_small_curse_effect': '詛咒效果',
  'vaal_small_fire_resistance': '火焰抗性',
  'vaal_small_cold_resistance': '冰冷抗性',
  'vaal_small_lightning_resistance': '閃電抗性',
  'vaal_small_chaos_resistance': '混沌抗性',

  // ── 卡魯伊 ──
  'karui_attribute_strength': '力量屬性',
  'karui_small_strength': '力量',
  'karui_notable_add_strength': '增加力量',
  'karui_notable_add_percent_strength': '增加百分比力量',
  'karui_notable_add_armour': '增加護甲',
  'karui_notable_add_leech': '增加偷取',
  'karui_notable_add_double_damage': '增加雙倍傷害',
  'karui_notable_add_life': '增加生命',
  'karui_notable_add_fortify_effect': '增加護體效果',
  'karui_notable_add_life_regen': '增加生命回復',
  'karui_notable_add_fire_resistance': '增加火焰抗性',
  'karui_notable_add_melee_damage': '增加近戰傷害',
  'karui_notable_add_damage_from_crits': '增加暴擊傷害',
  'karui_notable_add_melee_crit_chance': '增加近戰暴擊率',
  'karui_notable_add_burning_damage': '增加燃燒傷害',
  'karui_notable_add_totem_damage': '增加圖騰傷害',
  'karui_notable_add_melee_crit_multi': '增加近戰暴擊加成',
  'karui_notable_add_physical_damage': '增加物理傷害',
  'karui_notable_add_warcry_buff_effect': '增加戰吼增益效果',
  'karui_notable_add_totem_placement_speed': '增加圖騰放置速度',
  'karui_notable_add_stun_duration': '增加暈眩持續時間',
  'karui_notable_add_faster_burn': '加速燃燒',
  'karui_notable_add_reduced_stun_threshold': '降低暈眩門檻',
  'karui_notable_add_physical_added_as_fire': '物理傷害轉為火焰',
  'karui_notable_add_physical_taken_as_fire': '近戰擊中獲得盛怒',
  'karui_notable_add_endurance_charge_on_kill': '擊殺獲得耐力球',
  'karui_notable_add_intimidate': '恐嚇',

  // ── 馬拉乞 ──
  'maraketh_attribute_dex': '敏捷屬性',
  'maraketh_small_dex': '敏捷',
  'maraketh_notable_add_dexterity': '增加敏捷',
  'maraketh_notable_add_percent_dexterity': '增加百分比敏捷',
  'maraketh_notable_add_evasion': '增加閃避',
  'maraketh_notable_add_flask_charges': '增加藥劑充能',
  'maraketh_notable_add_speed': '增加速度',
  'maraketh_notable_add_life': '增加生命',
  'maraketh_notable_add_blind': '致盲',
  'maraketh_notable_add_movement_speed': '增加移動速度',
  'maraketh_notable_add_cold_resistance': '增加冰冷抗性',
  'maraketh_notable_add_projectile_damage': '增加投射物傷害',
  'maraketh_notable_add_ailment_avoid': '避免異常狀態',
  'maraketh_notable_add_global_crit_chance': '增加全域暴擊率',
  'maraketh_notable_add_poison_damage': '增加中毒傷害',
  'maraketh_notable_add_minion_damage': '增加召喚物傷害',
  'maraketh_notable_add_accuracy': '增加命中',
  'maraketh_notable_add_elemental_damage': '增加元素傷害',
  'maraketh_notable_add_aura_effect': '增加光環效果',
  'maraketh_notable_add_minion_movement_speed': '增加召喚物移動速度',
  'maraketh_notable_add_ailment_duration': '增加異常狀態持續時間',
  'maraketh_notable_add_faster_poison': '加速中毒',
  'maraketh_notable_add_ailment_effect': '增加異常狀態效果',
  'maraketh_notable_add_physical_added_as_cold': '物理傷害轉為冰冷',
  'maraketh_notable_add_flask_effect': '增加藥劑效果',
  'maraketh_notable_add_frenzy_charge_on_kill': '擊殺獲得狂怒球',
  'maraketh_notable_add_onslaught': '猛攻',

  // ── 聖堂 ──
  'templar_small_devotion': '信念',
  'templar_notable_devotion': '信念（卓越）',

  // ── 卡爾葛 ──
  'kalguuran_small_ward': '保護',
  'kalguuran_attribute_ward': '保護',
};

/** 把英文特殊天賦名稱翻譯為繁體中文（同時支援 Addition ID） */
export const translateAlternateSkillName = (englishName: string): string => {
  const normalized = englishName.trim();
  return alternateSkillNames[normalized] ?? alternateAdditionNames[normalized] ?? alternateSkillNames[englishName] ?? alternateAdditionNames[englishName] ?? englishName;
};

/** 把英文珠寶名稱翻譯為繁體中文 */
export const translateJewelName = (id: number, englishName: string): string => jewelNames[id] ?? englishName;

/** 把英文征服者名稱翻譯為繁體中文 */
export const translateConquerorName = (englishName: string): string => conquerorNames[englishName] ?? englishName;

export const englishFallbackTranslations: Record<string, string> = {
  'Divine Flesh': '神聖血肉',
  'Eternal Youth': '青春永駐',
  'Immortal Ambition': '不朽野望',
  'Corrupted Soul': '腐化之魂',
  'Glancing Blows': '側身之擊',
  'Wind Dancer': '風魔舞者',
  'The Agnostic': '不可知論',
  'Transcendence': '超凡脫俗',
  'Inner Conviction': '內觀信念',
  'Power of Purpose': '力量之意',
  'Supreme Decadence': '至高．頹廢',
  'Supreme Ego': '至高．自我',
  'Regenerate #% of Life per second': '每秒回復 #% 生命',
  '+# to Strength': '+# 力量',
  '+# to Dexterity': '+# 敏捷',
  '+#% to Melee Critical Strike Multiplier': '+#% 近戰暴擊加成',
  'Ignites you inflict deal Damage #% faster': '你造成的點燃傷害加速 #%',
  '#% increased Totem Placement speed': '增加 #% 圖騰放置速度',
  '#% increased Melee Critical Strike Chance': '增加 #% 近戰暴擊率',
  '#% increased Melee Damage': '增加 #% 近戰傷害',
  'Poisons you inflict deal Damage #% faster': '你造成的中毒傷害加速 #%',
  '#% increased Melee Physical Damage': '增加 #% 近戰物理傷害',
  'Bleeding you inflict deals Damage #% faster': '你造成的流血傷害加速 #%',
  '#% increased Spell Damage': '增加 #% 法術傷害',
  '#% increased Physical Damage': '增加 #% 物理傷害',
  '#% increased Fire Damage': '增加 #% 火焰傷害',
  '#% increased Cold Damage': '增加 #% 冰冷傷害',
  '#% increased Lightning Damage': '增加 #% 閃電傷害',
  '#% increased Chaos Damage': '增加 #% 混沌傷害',
  '#% increased Attack Speed': '增加 #% 攻擊速度',
  '+#% to Critical Strike Multiplier': '+#% 暴擊加成',
  '#% increased Armour': '增加 #% 護甲',
  '#% increased maximum Life': '增加 #% 生命最大值',
  '#% increased maximum Energy Shield': '增加 #% 能量護盾最大值',
  '+#% to Chaos Resistance': '+#% 混沌抗性',
  '#% increased Cast Speed': '增加 #% 施放速度',
  '#% increased Area of Effect': '增加 #% 範圍效果',
  '#% of Physical Damage Converted to Fire Damage': '#% 物理傷害轉換為火焰傷害',
  '#% of Physical Damage Converted to Cold Damage': '#% 物理傷害轉換為冰冷傷害',
  '#% of Physical Damage Converted to Lightning Damage': '#% 物理傷害轉換為閃電傷害',
  'Minions deal #% increased Damage': '召喚生物增加 #% 傷害',
  '#% increased Critical Strike Chance': '增加 #% 暴擊率',
  '#% increased Critical Strike Chance for Spells': '增加 #% 法術暴擊率',
  'Damage Penetrates #% Fire Resistance': '傷害穿透 #% 火焰抗性',
  'Damage Penetrates #% Cold Resistance': '傷害穿透 #% 冰冷抗性',
  'Damage Penetrates #% Lightning Resistance': '傷害穿透 #% 閃電抗性',
  '#% increased Area Damage': '增加 #% 範圍傷害',
  '+#% to maximum Fire Resistance': '+#% 火焰抗性上限',
  '+#% to maximum Cold Resistance': '+#% 冰冷抗性上限',
  '+#% to maximum Lightning Resistance': '+#% 閃電抗性上限',
  '+#% to maximum Chaos Resistance': '+#% 混沌抗性上限',
  '#% of Chaos Damage Leeched as Life': '#% 的混沌傷害轉為生命偷取',
  '#% of Physical Damage Leeched as Life': '#% 物理傷害轉為生命偷取',
  '#% of Fire Damage Leeched as Life': '#% 火焰傷害轉為生命偷取',
  '#% of Cold Damage Leeched as Life': '#% 冰冷傷害轉為生命偷取',
  '#% of Lightning Damage Leeched as Life': '#% 閃電傷害轉為生命偷取',
  '#% chance to deal Double Damage': '#% 機率造成 2 倍傷害',
  '#% of Spell Damage Leeched as Energy Shield': '#% 法術傷害轉為能量護盾偷取',
  '#% chance to inflict Withered for 2 seconds on Hit': '擊中時有 #% 機率造成凋零狀態，持續 2 秒',
  '+#% chance to Suppress Spell Damage': '+#% 壓抑法術傷害機率',
  '#% increased Burning Damage': '增加 #% 燃燒傷害',
  'Gain #% of Physical Damage as Extra Fire Damage': '獲得等同 #% 物理傷害的額外火焰傷害',
  '#% chance to Intimidate Enemies for 4 seconds on Hit': '擊中時有 #% 機率威嚇敵人 4 秒',
  'Gain #% of Physical Damage as Extra Cold Damage': '獲得等同 #% 物理傷害的額外冰冷傷害',
  '#% increased Elemental Damage': '增加 #% 元素傷害',
  '#% increased Endurance Charge Duration': '增加 #% 耐力球持續時間',
  '#% increased Power Charge Duration': '增加 #% 暴擊球持續時間',
  '#% increased Frenzy Charge Duration': '增加 #% 狂怒球持續時間',
  '#% faster start of Energy Shield Recharge': '能量護盾充能開始速度加快 #%',
  '#% Chance to Block Attack Damage': '增加 #% 攻擊傷害格擋率',
  'self_damaging_ailment_duration_+%': '你身上的傷害異常狀態持續時間 #%',
  '#% increased Ward': '增加 #% 保護',
  '#% faster Restoration of Ward': '#% 更快恢復保護',
  '#% increased Ward during any Flask Effect': '在任何藥劑效果期間增加 #% 保護',
  '#% chance for Ward to be Restored when you Use a Flask': '你使用藥劑時有 #% 機率恢復保護',
  'Gain # Endurance Charge when Ward Breaks': '保護破損時獲得 # 個耐力球',
  'Gain # Endurance Charges when Ward Breaks': '保護破損時獲得 # 個耐力球',
  'Gain # Power Charge when Ward Breaks': '保護破損時獲得 # 個暴擊球',
  'Gain # Power Charges when Ward Breaks': '保護破損時獲得 # 個暴擊球',
  'Gain # Frenzy Charge when Ward Breaks': '保護破損時獲得 # 個狂怒球',
  'Gain # Frenzy Charges when Ward Breaks': '保護破損時獲得 # 個狂怒球',
  '#% increased Armour while you have Unbroken Ward': '當你擁有未破損的保護時，增加 #% 護甲',
  '#% increased Evasion Rating while you have Unbroken Ward': '當你擁有未破損的保護時，增加 #% 閃避值',
  '+# to Ward per 10 Armour on Equipped Helmet': '裝備頭盔上的每 10 點護甲提供 +# 保護',
  '+# to Ward per 10 Evasion Rating on Equipped Gloves': '裝備手套上的每 10 點閃避值提供 +# 保護',
  '+# to Ward per 10 Energy Shield on Equipped Boots': '裝備鞋子上的每 10 點能量護盾提供 +# 保護',
  '#% increased Damage while you have Unbroken Ward': '當你擁有未破損的保護時，增加 #% 傷害',
  'Damage Penetrates #% Elemental Resistances while your Ward is Broken': '當你的保護破損時，傷害穿透 #% 元素抗性',
  '#% increased effect of Non-Curse Auras from your skills while your Ward is Broken':
    '當你的保護破損時，增加 #% 你技能的非詛咒光環效果',
  '#% chance to Restore Ward when you Block': '你格擋時有 #% 機率恢復保護',
  'Iron Flasks gain # charge when your Ward Breaks': '保護破損時，鐵製藥劑獲得 # 個充能',
  'Iron Flasks gain # charges when your Ward Breaks': '保護破損時，鐵製藥劑獲得 # 個充能',
  'Remove a random Damaging Ailment when Ward is Restored': '保護恢復時，移除一個隨機的傷害異常狀態',
  '#% increased Ward from Equipped Armour Items': '增加 #% 來自裝備護甲物品的保護',
  'Black Scythe Training': '黑鐮之訓',
  'Celestial Mathematics': '星界計算',
  'The Unbreaking Circle': '不滅之環',
  'Removes all Energy Shield\nChance to Evade Hits is based off of 200% of your Ward instead of your Evasion Rating\nPhysical Damage Reduction from Hits is based off of 200% of your Ward instead of your Armour':
    '移除所有能量護盾\n擊中閃避率改以你保護值的 200% 計算，而非閃避值\n擊中物理傷害減免改以你保護值的 200% 計算，而非護甲',
  'While you have Unbroken Ward, your next non-channelling Attack you Use yourself breaks your Ward to gain Added Cold Damage equal to 25% of Ward':
    '當你擁有未破損的保護時，你下一個由自己施放的非引導攻擊會打破你的保護，並獲得等同於保護 25% 的附加冰冷傷害',
  '40% less Ward\nWard has a 60% chance to not Break': '保護降低 40%\n保護有 60% 機率不會破損',
  'You gain Onslaught for # seconds on Kill': '擊殺時獲得 # 秒猛攻',
  '#% of Physical Damage Converted to Fire Damage while you have at least 150 Devotion':
    '若你至少有 150 個奉獻，將 #% 物理傷害轉換為火焰傷害',
  '#% of Physical Damage Converted to Cold Damage while you have at least 150 Devotion':
    '若你至少有 150 個奉獻，將 #% 物理傷害轉換為冰冷傷害',
  '#% of Physical Damage Converted to Lightning Damage while you have at least 150 Devotion':
    '若你至少有 150 個奉獻，將 #% 物理傷害轉換為閃電傷害',
  'Gain #% of Maximum Mana as Extra Maximum Energy Shield while you have at least 150 Devotion':
    '若你至少有 150 個奉獻，獲得等同 #% 最大魔力的額外最大能量護盾',
  '+# to Minimum Endurance Charges while you have at least 150 Devotion': '若你至少有 150 個奉獻，+# 最小耐力球',
  '+# to Minimum Power Charges while you have at least 150 Devotion': '若你至少有 150 個奉獻，+# 最小暴擊球',
  '+# to Minimum Frenzy Charges while you have at least 150 Devotion': '若你至少有 150 個奉獻，+# 最小狂怒球',
  '+#% to all maximum Resistances if you have at least 150 Devotion': '若你至少有 150 個奉獻，+#% 全部最大抗性',
  '#% chance to inflict Fire Exposure on Hit if you have at least 150 Devotion':
    '若你至少有 150 個奉獻，擊中時有 #% 機率造成火焰曝曬',
  '#% chance to inflict Cold Exposure on Hit if you have at least 150 Devotion':
    '若你至少有 150 個奉獻，擊中時有 #% 機率造成冰冷曝曬',
  '#% chance to inflict Lightning Exposure on Hit if you have at least 150 Devotion':
    '若你至少有 150 個奉獻，擊中時有 #% 機率造成閃電曝曬',
  '#% chance to gain a Frenzy Charge on Hit': '擊中時有 #% 機率獲得 1 個狂怒球',
  '#% chance to gain a Power Charge on Critical Strike': '暴擊時有 #% 機率獲得 1 個暴擊球',
  '#% increased Damage per Frenzy Charge': '每個狂怒球增加 #% 傷害',
  '#% increased Damage per Endurance Charge': '每個耐力球增加 #% 傷害',
  '#% increased Damage with Bleeding': '增加 #% 流血傷害',
  '#% increased Fire Damage with Attack Skills': '增加 #% 攻擊技能的火焰傷害',
  '#% increased Cold Damage with Attack Skills': '增加 #% 攻擊技能的冰冷傷害',
  '#% increased Lightning Damage with Attack Skills': '增加 #% 攻擊技能的閃電傷害',
  '#% increased Damage per Power Charge': '每個暴擊球增加 #% 傷害',
  "Gain # Endurance Charge every second if you've been Hit Recently": '若近期內被擊中，每秒獲得 # 個耐力球',
  '#% increased Strength': '增加 #% 力量',
  '#% increased Dexterity': '增加 #% 敏捷',
  '#% of Attack Damage Leeched as Life': '#% 攻擊傷害轉為生命偷取',
  '#% chance to gain an Endurance Charge on Kill': '擊殺時有 #% 機率獲得 1 個耐力球',
  '#% increased Warcry Buff Effect': '增加 #% 戰吼增益效果',
  '+# to maximum Fortification': '+# 最大護體',
  'Melee Hits grant # Rage': '近戰擊中時獲得 # 層盛怒',
  '#% Chance to deal Double Damage': '有 #% 機率造成雙倍傷害',
  '+#% to all maximum Fire Resistance': '+#% 所有最大火焰抗性',
  '+#% to all maximum Cold Resistance': '+#% 所有最大冰冷抗性',
  '+#% to all maximum Lightning Resistance': '+#% 所有最大閃電抗性',
  'Gain # Rage on Melee Hit': '近戰擊中時獲得 # 層盛怒',
  '#% increased Stun Duration on Enemies': '增加 #% 對敵人的暈眩時間',
  '#% increased Totem Damage': '增加 #% 圖騰傷害',
  '+#% to Fire Resistance': '+#% 火焰抗性',
  '+#% to Cold Resistance': '+#% 冰冷抗性',
  '+#% to Lightning Resistance': '+#% 閃電抗性',
  '#% increased Global Accuracy Rating': '增加 #% 命中值',
  '#% reduced Extra Damage from Critical Strikes': '減少 #% 受到的暴擊額外傷害',
  '#% reduced Enemy Stun Threshold': '減少 #% 敵人的暈眩門檻',
  '#% of Life Regenerated per second': '每秒回復 #% 生命',
  '#% increased Flask Effect Duration': '增加 #% 藥劑持續時間',
  '#% increased Mana Regeneration Rate': '增加 #% 魔法回復速度',
  '#% increased Minion Damage': '增加 #% 召喚生物傷害',
  '#% increased Minion Maximum Life': '增加 #% 召喚生物最大生命',
  '#% increased Brand Damage': '增加 #% 烙印傷害',
  '#% increased Trap Damage': '增加 #% 陷阱傷害',
  '#% increased Mine Damage': '增加 #% 地雷傷害',
  '#% increased Projectile Damage': '增加 #% 投射物傷害',
  '#% increased maximum Mana': '增加 #% 最大魔力',
  '#% increased Energy Shield Recharge Rate': '增加 #% 能量護盾回復速度',
  '+#% to all Elemental Resistances': '增加 #% 所有元素抗性',
  'Minions have #% increased maximum Life': '召喚生物增加 #% 最大生命',
  'Golems have #% more Life': '魔像有 #% 更多生命',
  'Life Recovery from Non-Instant Leech is not applied\n2% additional Physical Damage Reduction for every 3% Life Recovery per second from Leech':
    '來自非立即偷取的生命恢復不會套用\n來自偷取每秒每 3% 生命恢復，有 2% 額外物理傷害減免',
  '50% of Cold and Lightning Damage taken as Fire Damage\n50% less Cold Resistance\n50% less Lightning Resistance':
    '受到冰冷和閃電傷害的 50% 視為火焰傷害\n冰冷抗性總降 50%\n閃電抗性總降 50%',
  'Mana Recovery from Regeneration is not applied\n1 Rage Regenerated for every 25 Mana Regeneration per Second\nDoes not delay Inherent Loss of Rage\nSkills Cost +3 Rage':
    '不會套用至來自回復的魔力恢復\n每秒每 25 魔力回復產生 1 層盛怒\n無法延緩失去固有盛怒的速度\n技能消耗 +3 盛怒',
  'Flasks Gain 4 Charges per empty Flask Slot every 5 seconds': '每 5 秒藥劑根據每個空藥劑欄位獲得 4 充能',
  'Can\'t use Helmets\nYour Critical Strike Chance is Lucky\nYour Damage with Critical Strikes is Lucky\nEnemies\' Damage with Critical Strikes against you is Lucky':
    '不能使用頭盔\n你的暴擊率是幸運的\n你的暴擊傷害是幸運的\n敵人對你的暴擊傷害是幸運的',
  'You are Blind\nBlind does not affect your Light Radius\n25% more Melee Critical Strike Chance while Blinded':
    '你被致盲\n被致盲時不影響你的照亮範圍\n近戰暴擊率在被致盲時總增 25%',
  'Nearby Allies and Enemies Share Charges with you\nEnemies Hitting you have 10% chance to gain an Endurance, \nFrenzy or Power Charge':
    '附近友方和敵人與你共享能量球\n擊中你的敵人有 10% 機率獲得 1 顆耐力、\n狂怒或暴擊球',
  'Ignore Attribute Requirements\nGain no inherent bonuses from Attributes':
    '無視能力值需求\n不能獲得能力值既定的加成',
  '#% increased Projectile Speed': '增加 #% 投射物速度',
  '#% increased Skill Effect Duration': '增加 #% 技能持續時間',
  'Always Freezes Enemies on Hit': '擊中時總是凍結敵人',
  '#% increased Global Critical Strike Chance': '增加 #% 全域暴擊率',
  '#% increased Spell Critical Strike Chance': '增加 #% 法術暴擊率',
  '#% chance to Ignite': '有 #% 機率點燃',
  '#% chance to Shock': '有 #% 機率感電',
  '#% increased Area of Effect of Aura Skills': '增加 #% 光環技能效果範圍',
  '#% Global chance to Blind Enemies on hit': '全域擊中時有 #% 機率致盲敵人',
  '#% additional Physical Damage Reduction': '額外 #% 物理傷害減免',
  '+#% Chance to Block Attack Damage': '增加 #% 攻擊格擋機率',
  '# Life gained when you Block': '格擋時獲得 # 生命',
  '#% increased Effect of your Curses': '增加 #% 咒術效果',
  '#% increased Damage over Time': '增加 #% 持續傷害',
  '#% Chance to Block Spell Damage': '增加 #% 法術格擋機率',
  '#% increased Attack Damage': '增加 #% 攻擊傷害',
  '#% increased effect of Non-Curse Auras from your Skills': '增加 #% 技能中非咒術光環的效果',
  '#% chance to Avoid being Stunned': '有 #% 機率避免被暈眩',
  'Curse Skills have #% increased Skill Effect Duration': '咒術技能增加 #% 技能持續時間',
  '#% increased Flask Charges gained': '增加 #% 獲得的藥劑充能',
  'Minions have #% increased Movement Speed': '召喚生物增加 #% 移動速度',
  '#% chance to gain a Frenzy Charge on Kill': '擊殺時有 #% 機率獲得 1 個狂怒球',
  '#% increased Attack and Cast Speed': '增加 #% 攻擊與施放速度',
  '#% increased Attack, Cast and Movement Speed while you have Onslaught': '當你擁有猛攻時，增加 #% 攻擊、施放與移動速度',
  '#% increased Duration of Elemental Ailments on Enemies': '增加 #% 敵人身上的元素異常狀態持續時間',
  '#% increased Damage with Poison': '增加 #% 中毒傷害',
  '#% increased Effect of Non-Damaging Ailments': '增加 #% 非傷害型異常狀態效果',
  '#% chance to gain Alchemist\'s Genius when you use a Flask': '使用藥劑時有 #% 機率獲得「鍊金之材」',
  '+# to Devotion': '+# 奉獻',
  'Gain Arcane Surge on Hit with Spells if you have at least 150 Devotion': '若你至少有 150 個奉獻，法術擊中時獲得秘能波動',
  'Immune to Elemental Ailments while on Consecrated Ground if you have at least 150 Devotion': '若你至少有 150 個奉獻且在奉獻地面上，免疫元素異常狀態',
  '#% additional Physical Damage Reduction while you have at least 150 Devotion': '若你至少有 150 個奉獻，額外 #% 物理傷害減免',
  '#% chance to Avoid being Chilled': '有 #% 機率避免被冰緩',
  '#% chance to Avoid being Shocked': '有 #% 機率避免被感電',
  '#% increased Effect of Chill': '增加 #% 冰緩效果',
  '#% increased Effect of Shock': '增加 #% 感電效果',
  '#% increased Projectile Attack Damage': '增加 #% 投射物攻擊傷害',
  '#% increased Armour per Endurance Charge': '每個耐力球增加 #% 護甲',
  '#% increased Energy Shield per Power Charge': '每個暴擊球增加 #% 能量護盾',
  '#% increased Mana Reservation Efficiency of Skills': '增加 #% 技能魔力保留效能',
};

/** 優先使用繁中對照表，沒有時保留原模板，最終以英文字串比對作為防線 */
const lookupEnglishFallbackTranslation = (englishTemplate: string): string | undefined => {
  if (!englishTemplate) {
    return undefined;
  }

  return (
    englishFallbackTranslations[englishTemplate] ??
    englishFallbackTranslations[englishTemplate.replace(/\\n/g, '\n')] ??
    englishFallbackTranslations[englishTemplate.replace(/\n/g, '\\n')]
  );
};

export const getStatDescription = (id: number, englishTemplate: string): string =>
  lookupEnglishFallbackTranslation(englishTemplate) ?? statDescriptions[id] ?? englishTemplate;

/** 翻譯屬性文字並填入數值 */
export const translateStatText = (id: number, template: string, roll: number): string => {
  const localizedTemplate = getStatDescription(id, template);
  return localizedTemplate.replace('#', roll.toString());
};

/** 聯盟顯示名稱翻譯，保留 value 供 API / trade 使用 */
export const translateLeagueName = (englishName: string): string => {
  if (!englishName) {
    return englishName;
  }

  const normalized = englishName.trim();

  if (exactLeagueNames[normalized]) {
    return exactLeagueNames[normalized];
  }

  const directLowerMatch = exactLeagueNamesLower[normalized.toLowerCase()];
  if (directLowerMatch) {
    return directLowerMatch;
  }

  let translated = normalized;
  for (const [source, target] of leaguePhraseNames) {
    translated = translated.replace(new RegExp(source, 'gi'), target);
  }

  return translated.replace(/\s+/g, '');
};
